### ISSUE TITLE
Issue with config file

### ISSUE THREAD

**Issue by ABrambleNinja** [TalkTakesTime/Pokemon-Showdown-Bot#66]
I know this isn't being maintained anymore, but if anyone better at Node sees this and could help, I'd really appreciate it. When run, the bot complains that ``config.js`` doesn't exist, even though I'm 100% sure it does.

```
------------------------------------
| Welcome to Pokemon Showdown Bot! |
------------------------------------

error config.js doesn't exist; are you sure you copied config-example.js to config.js?
```
I tried copying the command and running it in the node REPL, and it was successful:

```
> global.Config = require('./config.js')
{ server: 'sim.psim.us',
  port: 8000,
  serverid: 'showdown',
  nick: 'Example bot nick',
  pass: '',
  rooms: [ 'example room name', 'another example' ],
...
```
I tried removing the try..catch statement to see what the exception that was raised was, and it was this:
```
/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:104
      throw err;
            ^
SyntaxError: /path/to/Pokemon-Showdown-Bot/package.json: Error while parsing JSON - Unexpected token ﻿
    at Object.parse (native)
    at OptionManager.addConfig (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/Pokemon-Showdown-Bot/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
I am not familiar with node, so I don't understand why requiring a config file would even look at packages.json., but there seems to be some issue with the babel package. Anyone have any ideas?

**Comment by Morfent** [comment]
This isn't an issue with the config file. That appears erroneously because Babel runs into three issues:
- On parsing `package.json` because it includes a byte order marking
- On attempting to install dependencies if they weren't already installed because the catch case uses return outside of a function
- On attempting to run `require('babel/register');` because babel-core wasn't included as a dependency
I'll fix these in a minute

**Comment by Morfent** [comment]
Fixed in https://github.com/TalkTakesTime/Pokemon-Showdown-Bot/commit/8df1a41db4f942ac84576c6d8393210648bf4633

**Comment by ABrambleNinja** [comment]
Thanks!
